#!/usr/bin/env bash
# Refresh the vendored quickjs-ng tree to a given upstream tag.
#
#   ./update_quickjs.sh v0.17.0
#
# Re-measure on the physical watch afterwards. Android x armv7 has no upstream CI coverage
# and no other Android project embeds quickjs-ng, so a green upstream release says nothing
# about this target — our device numbers are the only evidence that exists (ticket 06).
set -euo pipefail

TAG="${1:-}"
if [ -z "$TAG" ]; then
  echo "usage: $0 <upstream-tag>   e.g. $0 v0.17.0" >&2
  exit 1
fi

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST="$HERE/quickjs-ng"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> cloning quickjs-ng $TAG"
git clone --depth 1 --branch "$TAG" https://github.com/quickjs-ng/quickjs "$TMP/quickjs-ng"
COMMIT="$(git -C "$TMP/quickjs-ng" rev-parse HEAD)"

# Keep gen/ — upstream's qjs_exe/qjsc targets reference it at configure time, so removing it
# breaks CMake configuration even though we never build those targets.
rm -rf "$TMP/quickjs-ng/.git" \
       "$TMP/quickjs-ng/docs" \
       "$TMP/quickjs-ng/examples" \
       "$TMP/quickjs-ng/tests" \
       "$TMP/quickjs-ng/test262" \
       "$TMP/quickjs-ng/fuzz" \
       "$TMP/quickjs-ng/.github"

echo "==> replacing $DEST"
rm -rf "$DEST"
mv "$TMP/quickjs-ng" "$DEST"

cat > "$DEST/UPSTREAM.md" <<EOF
# Vendored quickjs-ng

**Upstream:** https://github.com/quickjs-ng/quickjs
**Tag:** \`$TAG\`
**Commit:** \`$COMMIT\`

Regenerated by \`update_quickjs.sh\`. See git history of this file for the
rationale notes that accompanied the original vendoring.
EOF

echo "==> now at $TAG ($COMMIT)"
echo "    re-measure on the watch: cold start, warm call, RSS, .so size"
