package com.liftosaur.wear

import com.liftosaur.wear.engine.WatchAmrapModal
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

/** The answers [PromptScreen] collects, in `completeSetWithAmrap`'s argument shape. */
data class PromptAnswers(
    val reps: Int? = null,
    val repsLeft: Int? = null,
    val weight: Double? = null,
    val rpe: Double? = null,
    val userVarsJson: String? = null,
)

/**
 * One page of the PAGED prompt.
 *
 * [options] are pre-rendered strings and [values] the parallel typed values, because a picker
 * option's *display* and its *meaning* diverge for weight (the modal supplies plate-legal
 * weights, which are not an arithmetic sequence) and for RPE (half steps). Deriving the value
 * from the index into the modal's own list is what keeps the weight page honest — the spec
 * requires it come from `validWeights`, not from a computed range.
 */
data class PromptField(
    val kind: Kind,
    val label: String,
    val options: List<String>,
    val values: List<Double>,
    val initialIndex: Int,
    /** Set only for user vars, which are keyed by name rather than by role. */
    val varName: String? = null,
    val varUnit: String? = null,
) {
    enum class Kind { REPS, REPS_LEFT, WEIGHT, RPE, USER_VAR }
}

private const val MAX_REPS = 50

/** Half steps 0..10, matching watchOS's `stride(from: 0, through: 10, by: 0.5)`. */
private val RPE_VALUES: List<Double> = generateSequence(0.0) { it + 0.5 }.takeWhile { it <= 10.0 }.toList()

/**
 * How far a user-var picker ranges either side of its current value.
 *
 * watchOS gives its crown an effectively unbounded -9999..9999 range, which a discrete picker
 * cannot reproduce without 20k options. A user var is a program state variable being nudged
 * between sessions, not typed from scratch, so a window around the current value covers the
 * real interaction; the cost is that a var cannot be moved more than this in one session.
 */
private const val USER_VAR_WINDOW = 100

fun promptFieldsFor(modal: WatchAmrapModal): List<PromptField> {
    val fields = mutableListOf<PromptField>()

    // Order mirrors AmrapModalView.swift: the unilateral left-side reps come first, so the
    // two reps pages read left-then-right rather than in the order the flags happen to sit in.
    if (modal.isAmrap && modal.isUnilateral) {
        fields += repsField(PromptField.Kind.REPS_LEFT, "Reps (left)", modal.initialRepsLeft)
    }
    if (modal.isAmrap) {
        val label = if (modal.isUnilateral) "Reps (right)" else "Reps"
        fields += repsField(PromptField.Kind.REPS, label, modal.initialReps)
    }
    if (modal.askWeight) {
        fields += weightField(modal)
    }
    if (modal.logRpe) {
        val initial = modal.initialRpe ?: 8.0
        fields += PromptField(
            kind = PromptField.Kind.RPE,
            label = "RPE",
            options = RPE_VALUES.map { formatNumber(it) },
            values = RPE_VALUES,
            initialIndex = RPE_VALUES.indexOfFirst { it >= initial }.coerceAtLeast(0),
        )
    }
    for (userVar in modal.userPromptedVars) {
        val start = userVar.value - USER_VAR_WINDOW
        val values = (0..USER_VAR_WINDOW * 2).map { start + it }
        val suffix = userVar.unit?.let { if (it == "%") "%" else " $it" } ?: ""
        fields += PromptField(
            kind = PromptField.Kind.USER_VAR,
            label = userVar.name,
            options = values.map { formatNumber(it) + suffix },
            values = values,
            initialIndex = USER_VAR_WINDOW,
            varName = userVar.name,
            varUnit = userVar.unit,
        )
    }
    return fields
}

private fun repsField(kind: PromptField.Kind, label: String, initial: Int?): PromptField {
    val values = (0..MAX_REPS).map { it.toDouble() }
    return PromptField(
        kind = kind,
        label = label,
        options = (0..MAX_REPS).map { it.toString() },
        values = values,
        initialIndex = (initial ?: 0).coerceIn(0, MAX_REPS),
    )
}

/**
 * The weight page, built from the modal's own `validWeights`.
 *
 * These are plate-legal weights for this exercise and gym, generated by the bundle and shipped
 * inline precisely so the watch needs no second JS call (spec §2.7). An empty list means the
 * bundle could not produce any, and a fabricated fallback range would offer weights the user
 * cannot load — so the field renders its current value alone rather than inventing options.
 */
private fun weightField(modal: WatchAmrapModal): PromptField {
    val weights = modal.validWeights?.takeIf { it.isNotEmpty() }
        ?: listOfNotNull(modal.initialWeight).ifEmpty { listOf(0.0) }
    val index = (modal.validWeightIndex ?: weights.indexOfFirst { it >= (modal.initialWeight ?: 0.0) })
        .coerceIn(0, weights.lastIndex)
    return PromptField(
        kind = PromptField.Kind.WEIGHT,
        label = "Weight",
        options = weights.map { "${formatNumber(it)} ${modal.weightUnit}" },
        values = weights,
        initialIndex = index,
    )
}

/**
 * Collects the picker selections into `completeSetWithAmrap`'s arguments.
 *
 * A field absent from [fields] stays null, which the bundle reads as "not asked for" — it is
 * not the same as zero, and passing a value for a field the modal did not raise would write it
 * into the set anyway.
 */
fun buildAnswers(fields: List<PromptField>, selections: List<Int>): PromptAnswers {
    var reps: Int? = null
    var repsLeft: Int? = null
    var weight: Double? = null
    var rpe: Double? = null
    val userVars = mutableMapOf<String, PromptField>()
    val userVarValues = mutableMapOf<String, Double>()

    fields.forEachIndexed { i, field ->
        val value = field.values.getOrNull(selections.getOrElse(i) { field.initialIndex }) ?: return@forEachIndexed
        when (field.kind) {
            PromptField.Kind.REPS -> reps = value.toInt()
            PromptField.Kind.REPS_LEFT -> repsLeft = value.toInt()
            PromptField.Kind.WEIGHT -> weight = value
            PromptField.Kind.RPE -> rpe = value
            PromptField.Kind.USER_VAR -> field.varName?.let {
                userVars[it] = field
                userVarValues[it] = value
            }
        }
    }

    return PromptAnswers(
        reps = reps,
        repsLeft = repsLeft,
        weight = weight,
        rpe = rpe,
        userVarsJson = userVars.takeIf { it.isNotEmpty() }?.let { vars ->
            buildJsonObject {
                for ((name, field) in vars) {
                    val value = userVarValues.getValue(name)
                    // Mirrors AmrapModalView.submitValues: a bare number when the var has no
                    // unit, {value, unit} when it does, and {value} alone for percentages —
                    // the bundle's Weight_isPct branch supplies the "%" itself.
                    when (field.varUnit) {
                        null -> put(name, JsonPrimitive(value))
                        "%" -> put(name, JsonObject(mapOf("value" to JsonPrimitive(value))))
                        else -> put(
                            name,
                            JsonObject(
                                mapOf(
                                    "value" to JsonPrimitive(value),
                                    "unit" to JsonPrimitive(field.varUnit),
                                ),
                            ),
                        )
                    }
                }
            }.toString()
        },
    )
}

fun formatNumber(value: Double): String =
    if (value % 1.0 == 0.0) value.toInt().toString() else value.toString()
